---------------------
-- Add CC Licenses -- 
---------------------
INSERT INTO [mc].[License]([Id],[Version],[ViewOrder],[Abbreviation],[Title],[Url],[ImageUrl],[Description])
	VALUES (NEWID(),GETDATE(),1,'by','Attribution','http://creativecommons.org/licenses/by/3.0','http://i.creativecommons.org/l/by/3.0/88x31.png','This license lets others distribute, remix, tweak, and build upon your work, even commercially, as long as they credit you for the original creation. This is the most accommodating of licenses offered, in terms of what others can do with your works licensed under Attribution.');
INSERT INTO [mc].[License]([Id],[Version],[ViewOrder],[Abbreviation],[Title],[Url],[ImageUrl],[Description])
	VALUES (NEWID(),GETDATE(),2,'by-sa','Attribution-ShareAlike','http://creativecommons.org/licenses/by-sa/3.0','http://i.creativecommons.org/l/by-sa/3.0/88x31.png','This license lets others remix, tweak, and build upon your work even for commercial reasons, as long as they credit you and license their new creations under the identical terms. This license is often compared to open source software licenses. All new works based on yours will carry the same license, so any derivatives will also allow commercial use.');
INSERT INTO [mc].[License]([Id],[Version],[ViewOrder],[Abbreviation],[Title],[Url],[ImageUrl],[Description])
	VALUES (NEWID(),GETDATE(),3,'by-nd','Attribution-NoDerivs','http://creativecommons.org/licenses/by-nd/3.0','http://i.creativecommons.org/l/by-nd/3.0/88x31.png','This license allows for redistribution, commercial and non-commercial, as long as it is passed along unchanged and in whole, with credit to you.');
INSERT INTO [mc].[License]([Id],[Version],[ViewOrder],[Abbreviation],[Title],[Url],[ImageUrl],[Description])
	VALUES (NEWID(),GETDATE(),4,'by-nc','Attribution-NonCommercial','http://creativecommons.org/licenses/by-nc/3.0','http://i.creativecommons.org/l/by-nc/3.0/88x31.png','This license lets others remix, tweak, and build upon your work non-commercially, and although their new works must also acknowledge you and be non-commercial, they don’t have to license their derivative works on the same terms.');
INSERT INTO [mc].[License]([Id],[Version],[ViewOrder],[Abbreviation],[Title],[Url],[ImageUrl],[Description])
	VALUES (NEWID(),GETDATE(),5,'by-nc-sa','Attribution-NonCommercial-ShareAlike','http://creativecommons.org/licenses/by-nc-sa/3.0','http://i.creativecommons.org/l/by-nc-sa/3.0/88x31.png','This license lets others remix, tweak, and build upon your work non-commercially, as long as they credit you and license their new creations under the identical terms. Others can download and redistribute your work just like the by-nc-nd license, but they can also translate, make remixes, and produce new stories based on your work. All new work based on yours will carry the same license, so any derivatives will also be non-commercial in nature.');
INSERT INTO [mc].[License]([Id],[Version],[ViewOrder],[Abbreviation],[Title],[Url],[ImageUrl],[Description])
	VALUES (NEWID(),GETDATE(),6,'by-nc-nd','Attribution-NonCommercial-NoDerivs','http://creativecommons.org/licenses/by-nc-nd/3.0','http://i.creativecommons.org/l/by-nc-nd/3.0/88x31.png','This license is the most restrictive of our six main licenses, allowing redistribution. This license is often called the “free advertising” license because it allows others to download your works and share them with others as long as they mention you and link back to you, but they can’t change them in any way or use them commercially.');
GO